services:
  omarket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7558
      - ASPNETCORE_HTTPS_PORTS=7557
    ports:
      - "7558:7558"
      - "7557:7557"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - C:/path/to/host/storage:/home/app/.aspnet/DataProtection-Keys
      - C:/path/to/host/logs:/home/app/logs